Improve XXE attack module
wapiti-scanner/wapiti pull request #245
Opened 2022-02-09 15:12 UTC by devl00p

2022-02-09 15:27 UTC, devl00p commented
Two improvements : 
* Add two more XXE payloads (one for Unix, one for Windows) that doesn't use php filters
* Generate a medium vulnerability report when the DTD was reached but no data was exfiltrated

![wapiti_xxe](https://user-images.githubusercontent.com/20163212/153232498-5d55009c-00c9-479b-a0d8-8742a8007093.gif)

2022-02-09 15:28 UTC, devl00p commented
Fix #81

2022-02-09 15:31 UTC, devl00p commented
Exfiltration tested against https://pentesterlab.com/exercises/play_xxe/course (Java based app)

2022-02-15 07:26 UTC, JulienTD requested changes

2022-02-15 07:26 UTC, JulienTD commented on endpoint/get_xxe.php
> +	    // ./xxe_data/<session_id>/<path_id>/<hex_param>/<filename>
maybe remove this comment or rearrange it to follow the other lines  indentation and a description

2022-02-15 07:26 UTC, JulienTD commented on endpoint/xxe_dtd.php
> +if (substr($payload, 0, 4 ) === "java") {
there is an extra space after the 4, should be: `if (substr($payload, 0, 4) === "java") {`

2022-02-15 12:54 UTC, merged