Modified the --update flag to permits the user to choose what modules to update
wapiti-scanner/wapiti pull request #257
Opened 2022-02-16 12:05 UTC by JulienTD

## Description
Currently, when we want to update a specific module we need to pass --update as an argument to wapiti, but it will update every module.
In this PR, I have added the possibility for the user to choose what module to update, it works the same as the attack module selector (moduleA,moduleB or all).  
Example: `wapiti --update all` or `wapiti --update wapp,nikto`
## Related Issue(s)
fixes #254

2022-02-16 15:22 UTC, polyedre commented
It's not clean to break the current behavior. Can you do something like:

```sh
# Update all the packages, the default
cyberwatch --update
# update only nikto and htb
wapiti --update --module nikto,htp
```

2022-02-16 15:40 UTC, JulienTD commented
> It's not clean to break the current behavior. Can you do something like:
> 
> ```shell
> # Update all the packages, the default
> wapiti --update
> # update only nikto and htb
> wapiti --update --module nikto,htp
> ```

Ok done! Now you can use `wapiti --update` or `wapiti --update -m nikto,htp`

2022-02-16 15:41 UTC, polyedre requested changes

2022-02-16 15:41 UTC, polyedre commented on wapitiCore/main/wapiti.py
> +    async def update(self, raw_modules: str = "all"):
Other than that, looks good to me! Thanks

2022-02-16 17:37 UTC, bretfourbe approved these changes

2022-02-18 20:22 UTC, devl00p commented
Nicely done

2022-02-18 20:22 UTC, merged