Fix #394: Network issues and crawlers improvements
wapiti-scanner/wapiti pull request #422
Opened 2023-07-10 15:56 UTC by Darkiros

Fix issue #394.

* I fix the network issues with a new configuration in `crawler.py` : 
```python
self._timeout = httpx.Timeout(timeout, read=None)
```

I did many tests to decide how to do. And here is some element to compare why None is better : 

Here with 10s in read timeout
![image](https://github.com/wapiti-scanner/wapiti/assets/37926502/72f50eee-97a4-46ba-8661-94487d03a5ca)

Here with None in read timeout
![image](https://github.com/wapiti-scanner/wapiti/assets/37926502/173b7125-8ff9-4915-9a72-55d58742e02e)

The crawler is faster and crawl more URL than with 10s timeout. There is no chance to be stuck with the response delay because connect, pool and write timer are set to default or -t option.

* I also set a new param in different send request to allow the overwriting of the new crawler configuration for some modules like `timesql` and change the `read=None` to the -t or the default value.

* I change the timeout in headless crawler to fit with the -t option instead of constant value.

* I make changes with the new behaviour in test_network_issues modules.

2023-07-10 18:13 UTC, Slokilla requested changes

2023-07-10 18:13 UTC, Slokilla commented on wapitiCore/net/crawler.py
> +            request = self._client.build_request("GET", resource.url, headers=headers, timeout=timeout)
a more compact way is 
```suggestion
        timeout = self.timeout if timeout is none else httpx.Timeout(timeout)
        request = self._client.build_request("GET", resource.url, headers=headers, timeout=timeout)

```

2023-07-10 18:13 UTC, Slokilla commented on wapitiCore/net/crawler.py
> +            )
Idem for below usage

2023-07-11 18:41 UTC, devl00p commented on wapitiCore/attack/attack.py
> +    async def does_timeout(self, request, timeout = None):
can you add type annotation please ?

2023-07-12 13:46 UTC, merged