adding base integration test system
wapiti-scanner/wapiti pull request #438
Opened 2023-07-25 15:01 UTC by RMI78

MR for the integration test system. This is the base system with the documentation, tests will come once this MR will be merged.

As of today, I can and will provide integration tests for the following modules:
- backup 
- wp_enum 
- drupal_enum
- brute_login_form 
- cookieflags 
- crlf 
- csp 
- exec 
- file 
- htaccess 
- http_headers 
- xss 
- shellshock 
- methods 
- timesql 
- wapp
- permanentxss
- log4shell
- redirect
- ssrf

As well as a test for the crawler and its different way to handle redirections, plus a test for every authenticating methods it does. 

You can look up in the documentation to see how it works

2023-07-27 18:24 UTC, Slokilla requested changes

2023-07-27 18:24 UTC, Slokilla commented on .gitignore
> +tests/integrations/docker-compose.solo_setup.yml
```suggestion

```

2023-07-27 18:24 UTC, Slokilla commented on tests/integration/check.sh
> +# (except their extention names, .txt and .out) we extract the targets names
```suggestion
# (except their extention names, .json and .out) we extract the targets names
```
no ?

2023-07-27 18:24 UTC, Slokilla commented on tests/integration/check.sh
> +
```suggestion

```

2023-07-27 18:24 UTC, Slokilla commented on tests/integration/run.sh
> +# List of the currently working tests
```suggestion
# List of modules to be tested
```
is more accurate ?

2023-07-27 18:24 UTC, Slokilla commented on tests/integration/wapiti/Dockerfile.integration
> +
```suggestion

```

2023-07-28 09:11 UTC, fwininger approved these changes

2023-07-28 09:34 UTC, bretfourbe approved these changes

2023-07-28 12:20 UTC, merged