distributed docker-compose file with adapted run.sh
wapiti-scanner/wapiti pull request #475
Opened 2023-08-07 14:58 UTC by RMI78

This MR simplifies the integration testing system by splitting the docker-compose file. It should optimize things a lot since it will not launch all the services at once when only some tests are required. The build time will be decreased, and some tests can be fully disabled if they break (without breaking the hole system), and we don't care or if we simply want to disable them for reason X.

Building new integration tests will, by consequence, be faster as you can only build your targets

The file run.sh also had a full refactoring, so understanding the changes might not be easy

2023-08-07 15:18 UTC, RMI78 commented
Still a work in progress, too much output, some working in progress with docker compose build and some repeated code can be simplified

2023-08-09 14:48 UTC, bretfourbe approved these changes

2023-08-10 06:44 UTC, Slokilla requested changes

2023-08-10 06:44 UTC, Slokilla commented on tests/integration/run.sh
> +    DOCKER_COMPOSE_CONFIG_ARGUMENT+="-f ./${test//$'\n'/}/docker-compose.setup.yml "
c'est voulu l'espace finale ?

2023-08-10 06:44 UTC, Slokilla commented on tests/integration/run.sh
> +docker compose --progress quiet --project-directory ./ -f .docker-compose.final.yml ${DOCKER_COMPOSE_UP_ARGUMENT}
pour des docker compose up argument, c'est pas pratique de mettre des espaces dans les chaines. On a pas un magie blanche en bash pour faire un [arg1, arg2].join(' ') ?

2023-08-10 07:12 UTC, RMI78 commented on tests/integration/run.sh
> +docker compose --progress quiet --project-directory ./ -f .docker-compose.final.yml ${DOCKER_COMPOSE_UP_ARGUMENT}
L'idée serait de stocker les arguments dans un tableau plutôt que dans une chaine ?

2023-08-10 09:40 UTC, merged