{url,page,folder,domain,punk}
wapiti-scanner/wapiti pull request #530
Opened 2023-11-21 09:14 UTC by deadjdona

Proper order of parameters in --scope

2023-11-21 09:38 UTC, Slokilla commented
Thanks for clearing your previous merge request ! I think you can squash all this commits into one “Ordering scope parameters orders” commit and it will be good for review :)

2023-11-21 16:39 UTC, Slokilla requested changes

2023-11-21 16:39 UTC, Slokilla commented on doc/wapiti.1
> +\fB\-\-scope\fR {url,page,folder,domain,punk}
```suggestion
\fB\-\-scope\fR {url,page,folder,subdomain,domain,punk}
```

2023-11-21 16:39 UTC, Slokilla commented on doc/wapiti.ronn
> +  * `--scope` {url,page,folder,domain,punk}
```suggestion
  * `--scope` {url,page,folder,subdomain,domain,punk}
```

2023-11-21 16:39 UTC, Slokilla commented on doc/wapiti.1.html
> +<li><code>--scope</code> {url,page,folder,domain,punk}</li>
```suggestion
<li><code>--scope</code> {url,page,folder,subdomain,domain,punk}</li>
```

2024-02-12 10:45 UTC, bretfourbe commented
@deadjdona, https://github.com/wapiti-scanner/wapiti/pull/558 is merged so I close this one, thanks for contributing

2024-02-12 10:45 UTC, closed without merging