Fix the issue #559
wapiti-scanner/wapiti pull request #562
Opened 2024-02-16 18:51 UTC by OussamaBeng

Fixing the errors logging

2024-02-20 13:58 UTC, Qwarctick commented
Note: This PR is related to https://github.com/wapiti-scanner/wapiti/issues/559

I think this does not work as expected. If I try your code : 

``` bash
bin/wapiti --update --wapp-url qwerty

 ██╗    ██╗ █████╗ ██████╗ ██╗████████╗██╗██████╗
 ██║    ██║██╔══██╗██╔══██╗██║╚══██╔══╝██║╚════██╗
 ██║ █╗ ██║███████║██████╔╝██║   ██║   ██║ █████╔╝
 ██║███╗██║██╔══██║██╔═══╝ ██║   ██║   ██║ ╚═══██╗
 ╚███╔███╔╝██║  ██║██║     ██║   ██║   ██║██████╔╝
  ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝     ╚═╝   ╚═╝   ╚═╝╚═════╝
Wapiti 3.1.8 (wapiti-scanner.github.io)
[*] Updating modules
Updating module htp
Update done.
Updating module wapp
Error: Non-200 status code for _.json. Skipping.
RequestError occurred: Request URL is missing an 'http://' or 'https://' protocol.
RequestError during update: Request URL is missing an 'http://' or 'https://' protocol.
[!] Module wapp seems broken and will be skipped
Updating module nikto
Update done.
Error: None is not a valid domain name
```
You should have one or two error message, not duplicate of them. And there is a mix of error message.

2024-02-29 14:58 UTC, bretfourbe approved these changes

2024-02-29 15:14 UTC, Qwarctick commented
Seems good:

``` python
$ bin/wapiti --update --wapp-url kjhdsdkfhdsf

 ██╗    ██╗ █████╗ ██████╗ ██╗████████╗██╗██████╗
 ██║    ██║██╔══██╗██╔══██╗██║╚══██╔══╝██║╚════██╗
 ██║ █╗ ██║███████║██████╔╝██║   ██║   ██║ █████╔╝
 ██║███╗██║██╔══██║██╔═══╝ ██║   ██║   ██║ ╚═══██╗
 ╚███╔███╔╝██║  ██║██║     ██║   ██║   ██║██████╔╝
  ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝     ╚═╝   ╚═╝   ╚═╝╚═════╝
Wapiti 3.1.8 (wapiti-scanner.github.io)
[*] Updating modules
Updating module wapp
Error: kjhdsdkfhdsf is not a valid URL
Invalid Option Error :
[!] Module wapp seems broken and will be skipped
Updating module nikto
Update done.
Updating module htp
Update done.
Error: None is not a valid domain name
```

2024-02-29 15:15 UTC, Qwarctick approved these changes

2024-02-29 16:54 UTC, Qwarctick requested changes

2024-02-29 16:54 UTC, Qwarctick commented on wapitiCore/controller/wapiti.py
> +                            logging.error("Invalid Option Error :")
You can print the error directly from the exception as `InvalidOptionValue` implements `__str__`.

``` python
except InvalidOptionValue as invalid_option_value:
    logging.error(invalid_option_value)
```

2024-02-29 16:54 UTC, Qwarctick commented on wapitiCore/controller/wapiti.py
> +                            logging.error("Request Error :")
You can print the error directly from the exception as `InvalidOptionValue` implements `__str__`.

``` python
except RequestError as request_error:
    logging.error(request_error)
```

2024-02-29 16:54 UTC, Qwarctick commented on wapitiCore/attack/mod_wapp.py
> +            logging.error(f"RequestError occurred: {e}")
You should just raise again the error. Remove the logging to avoid duplication.

2024-03-01 09:52 UTC, merged