Add Module : WordPress Plugins detect
wapiti-scanner/wapiti pull request #68
Opened 2021-02-18 17:44 UTC by OussamaBeng

Adding module to detect name and version of the installed plugins in WordPress websites

2021-02-19 20:02 UTC, fwininger approved these changes
Seems a very great feature ! Thanks

2021-02-19 20:04 UTC, fwininger commented
@jinxka take a look

2021-02-20 17:39 UTC, bretfourbe approved these changes
It would be nice to add tests for this module

2021-02-21 17:09 UTC, devl00p requested changes

2021-02-21 17:09 UTC, devl00p commented on wapitiCore/attack/mod_cms.py
> +class mod_cms(Attack):
If it is specific to Wordpress you should rename to `mod_wordpress_plugins` or `mod_wordpress_enumeration` so it is more clear

2021-02-21 17:09 UTC, devl00p commented on wapitiCore/attack/mod_cms.py
> +            req= Request('{}/wp-content/plugins/{}/readme.txt'.format(url, plugin))
Can you please fix whitespaces around operators to comply with PEP8 recommandations ? https://www.python.org/dev/peps/pep-0008/#other-recommendations

2021-02-28 08:05 UTC, devl00p commented on wapitiCore/attack/mod_cms.py
> +class mod_cms(Attack):
`mod_wpenum` would be short and meaningful I guess

2021-03-19 19:43 UTC, bretfourbe approved these changes

2021-03-23 20:03 UTC, devl00p commented
Nice, than for your work

2021-03-23 20:03 UTC, merged